# LOCATION: backend/src/app/jobs/workers/export_worker.py
from __future__ import annotations

from typing import Any, Dict, List, Optional


def run_export(context: Any, payload: Dict[str, Any]) -> Dict[str, Any]:
    """
    Export worker (Phase 1 / V1)

    Contract:
      - MUST return dict
      - Produces a "playlist plan" (not creating it on YouTube in V1)

    Expected payload:
      - user_id: str|int (recommended)
      - items: list[dict] optional (candidate tracks chosen by UI)
      - title: str optional
      - description: str optional

    Output:
      {"ok": bool, "data": {"playlist": {...}}, "errors": [...]}
    """
    errors: List[str] = []
    user_id = payload.get("user_id")

    title = payload.get("title") or "Music Rewind — Recovered Songs"
    description = payload.get("description") or "Generated by Music Rewind."
    items = payload.get("items") or []

    if not isinstance(items, list):
        return {
            "ok": False,
            "user_id": user_id,
            "data": {},
            "errors": ["items must be a list"],
        }

    # V1: build a deterministic export payload the UI can download / preview.
    # Later: a write-scope worker can actually create playlist on YouTube.
    playlist = {
        "title": title,
        "description": description,
        "items": items,
        "count": len(items),
    }

    return {
        "ok": len(errors) == 0,
        "user_id": user_id,
        "data": {"playlist": playlist},
        "errors": errors,
    }


__all__ = ["run_export"]